"""
Decision Engine — central gate that determines whether implementation is
allowed for a given hypothesis / evidence-passport pair.

Usage::

    registry = HypothesisRegistry("ledger.json")
    engine = DecisionEngine(registry)
    decision = engine.is_implementation_allowed(card_id, passport)
    if decision.implementation_allowed:
        ...  # proceed
    else:
        logger.warning("Blocked: %s", decision.blocked_reason)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from lib.evidence_engine.claims import Claim, ClaimStatus, ClaimType
from lib.evidence_engine.evidence_passport import EvidencePassport
from lib.evidence_engine.gate_mapping import GateMapper, GateResult
from lib.evidence_engine.hard_caps import HardCapResult
from lib.evidence_engine.hypothesis import HypothesisRegistry

# ---------------------------------------------------------------------------
# Decision
# ---------------------------------------------------------------------------


@dataclass
class Decision:
    """Result of evaluating a claim or implementation request."""

    claim_id: str
    claim_type: str
    verdict: str  # ACCEPTED | REJECTED | INSUFFICIENT_EVIDENCE
    implementation_allowed: bool
    blocked_reason: str | None = None
    blocked_actions: list[str] = field(default_factory=list)
    allowed_actions: list[str] = field(default_factory=list)
    required_steps: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# DecisionEngine
# ---------------------------------------------------------------------------


class DecisionEngine:
    """Central authority for evidence-based implementation decisions.

    Decisions are generated by evaluating a ``Claim`` against an
    ``EvidencePassport``, or by the convenience method
    ``is_implementation_allowed`` which checks the full decision chain.
    """

    # Maximum trials before a hypothesis expires.
    _MAX_TRIALS_OVERRIDE: int | None = None  # None = use card's own max_trials

    def __init__(self, hypothesis_registry: HypothesisRegistry) -> None:
        self._registry = hypothesis_registry
        self._gate_mapper = GateMapper()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def evaluate_claim(
        self,
        claim: Claim,
        passport: EvidencePassport,
    ) -> Decision:
        """Evaluate a single claim against an evidence passport.

        This is the core reasoning step: it reads relevant fields from
        the passport, applies thresholds, and returns a verdict.
        """
        claim_type = claim.claim_type
        metrics = passport.metrics
        baselines = passport.baselines
        hard_caps = passport.hard_caps
        verdict: str
        allowed: bool
        blocked: str | None = None
        blocked_actions: list[str] = list(hard_caps.blocked_actions)
        allowed_actions: list[str] = list(hard_caps.allowed_actions)
        required_steps: list[str] = []
        warnings: list[str] = EvidencePassportBuilder.validate(passport)

        # Verify basic passport structure first
        if not metrics:
            return Decision(
                claim_id=claim.claim_id,
                claim_type=claim_type.value,
                verdict="INSUFFICIENT_EVIDENCE",
                implementation_allowed=False,
                blocked_reason="Passport has no metrics",
                blocked_actions=["ALL_ACTIONS"],
                required_steps=["Re-run training pipeline"],
            )

        # Route by claim type
        if claim_type == ClaimType.ALPHA_HAS_EDGE:
            verdict, allowed, blocked, required_steps = (
                self._eval_alpha_has_edge(metrics)
            )
        elif claim_type == ClaimType.MODEL_BEATS_BASELINES:
            verdict, allowed, blocked, required_steps = (
                self._eval_model_beats_baselines(metrics, baselines)
            )
        elif claim_type == ClaimType.FEATURE_FAMILY_HAS_SIGNAL:
            verdict, allowed, blocked, required_steps = (
                self._eval_feature_signal(metrics)
            )
        elif claim_type == ClaimType.COST_AWARE_FILTER_IMPROVES_NET_R:
            verdict, allowed, blocked, required_steps = (
                self._eval_cost_aware_filter(metrics)
            )
        elif claim_type == ClaimType.TRAINING_CHANGE_ALLOWED:
            verdict, allowed, blocked, required_steps = (
                self._eval_training_change(metrics)
            )
        elif claim_type in (
            ClaimType.V7_RESEARCH_BACKTEST_READY,
            ClaimType.V7_COST_STRESS_READY,
            ClaimType.V7_SHADOW_READY,
            ClaimType.V7_PAPER_READY,
        ):
            verdict, allowed, blocked, required_steps = (
                self._eval_v7_readiness(claim_type, passport)
            )
        else:
            verdict = "INSUFFICIENT_EVIDENCE"
            allowed = False
            blocked = f"Unknown claim_type: {claim_type}"

        return Decision(
            claim_id=claim.claim_id,
            claim_type=claim_type.value,
            verdict=verdict,
            implementation_allowed=allowed,
            blocked_reason=blocked,
            blocked_actions=blocked_actions,
            allowed_actions=allowed_actions,
            required_steps=required_steps,
            warnings=warnings,
        )

    def is_implementation_allowed(
        self,
        hypothesis_card_id: str,
        passport: EvidencePassport,
    ) -> Decision:
        """The critical implementation gate.

        Checks in order:

        1. Hypothesis card is registered + approved (or at least not rejected).
        2. Evidence passport exists and has metrics.
        3. Hard caps do not block.
        4. Baseline comparisons exist.
        5. Trial count does not exceed max_trials.
        """
        claim_id = f"impl-{hypothesis_card_id}"

        # 1. Hypothesis card
        card = self._registry.get(hypothesis_card_id)
        if card is None:
            return Decision(
                claim_id=claim_id,
                claim_type="IMPLEMENTATION_CHECK",
                verdict="REJECTED",
                implementation_allowed=False,
                blocked_reason=(
                    f"Hypothesis card '{hypothesis_card_id}' not found in registry"
                ),
                required_steps=["Register a hypothesis card first"],
            )
        if card.status not in ("REGISTERED", "APPROVED"):
            return Decision(
                claim_id=claim_id,
                claim_type="IMPLEMENTATION_CHECK",
                verdict="REJECTED",
                implementation_allowed=False,
                blocked_reason=(
                    f"Hypothesis card status is '{card.status}', "
                    f"expected REGISTERED or APPROVED"
                ),
                required_steps=[
                    f"Set card status to REGISTERED or APPROVED "
                    f"(current: {card.status})",
                ],
            )

        # 2. Evidence passport
        if not passport or not passport.metrics:
            return Decision(
                claim_id=claim_id,
                claim_type="IMPLEMENTATION_CHECK",
                verdict="INSUFFICIENT_EVIDENCE",
                implementation_allowed=False,
                blocked_reason="Evidence passport is empty or has no metrics",
                required_steps=["Run training pipeline to produce evidence"],
            )

        # 3. Hard caps
        if passport.hard_caps.blocked_actions:
            return Decision(
                claim_id=claim_id,
                claim_type="IMPLEMENTATION_CHECK",
                verdict="REJECTED",
                implementation_allowed=False,
                blocked_reason="Hard caps block implementation",
                blocked_actions=list(passport.hard_caps.blocked_actions),
                allowed_actions=list(passport.hard_caps.allowed_actions),
                required_steps=[
                    f"Resolve hard-cap blocks: "
                    f"{'; '.join(passport.hard_caps.blocked_actions)}",
                ],
            )

        # 4. Baseline comparisons
        if not passport.baselines:
            return Decision(
                claim_id=claim_id,
                claim_type="IMPLEMENTATION_CHECK",
                verdict="INSUFFICIENT_EVIDENCE",
                implementation_allowed=False,
                blocked_reason="No baseline comparisons in passport",
                required_steps=["Run baseline library against training output"],
            )

        # 5. Trial count
        effective_max = (
            self._MAX_TRIALS_OVERRIDE
            if self._MAX_TRIALS_OVERRIDE is not None
            else card.max_trials
        )
        if passport.trial_count >= effective_max:
            return Decision(
                claim_id=claim_id,
                claim_type="IMPLEMENTATION_CHECK",
                verdict="REJECTED",
                implementation_allowed=False,
                blocked_reason=(
                    f"Trial count {passport.trial_count} >= max {effective_max}"
                ),
                required_steps=[
                    "Hypothesis has expired — file a new hypothesis card",
                ],
            )

        # All checks passed
        return Decision(
            claim_id=claim_id,
            claim_type="IMPLEMENTATION_CHECK",
            verdict="ACCEPTED",
            implementation_allowed=True,
            allowed_actions=list(passport.hard_caps.allowed_actions)
            or ["FULL_IMPLEMENTATION"],
            required_steps=[],
        )

    def get_allowed_actions(
        self,
        passport: EvidencePassport,
    ) -> list[str]:
        """Return actions that are *not* blocked by hard caps.

        If hard caps do not specify allowed_actions, returns a sensible
        default based on gate-passing status.
        """
        if passport.hard_caps.allowed_actions:
            return list(passport.hard_caps.allowed_actions)

        # Fallback: derive from gates
        gate_results = self._gate_mapper.map_passport_to_gates(passport)
        progress = self._gate_mapper.get_overall_progress(gate_results)

        actions: list[str] = []
        # G0 passed -> code is safe
        if gate_results.get("G0", GateResult("G0", "", "NOT_RUN")).status == "PASSED":
            actions.append("CODE_REFACTOR")
        # G1 passed -> basic research backtest ready
        if gate_results.get("G1", GateResult("G1", "", "NOT_RUN")).status == "PASSED":
            actions.append("RESEARCH_BACKTEST")
        # G2 passed -> walk-forward ready
        if gate_results.get("G2", GateResult("G2", "", "NOT_RUN")).status == "PASSED":
            actions.append("WALK_FORWARD_VALIDATION")
        # G3 passed -> cost stress ready
        if gate_results.get("G3", GateResult("G3", "", "NOT_RUN")).status == "PASSED":
            actions.append("COST_STRESS_TEST")
        # G7 passed -> shadow paper ready
        if gate_results.get("G7", GateResult("G7", "", "NOT_RUN")).status == "PASSED":
            actions.append("SHADOW_PAPER")

        if not actions and progress.get("passed", 0) == 0:
            actions.append("RESEARCH_CANDIDATE")

        return actions

    def get_blocked_actions(
        self,
        passport: EvidencePassport,
    ) -> list[str]:
        """Return actions explicitly blocked by hard caps."""
        return list(passport.hard_caps.blocked_actions)

    # ------------------------------------------------------------------
    # Claim evaluators
    # ------------------------------------------------------------------

    @staticmethod
    def _eval_alpha_has_edge(metrics: dict) -> tuple[str, bool, str | None, list[str]]:
        net_exp = metrics.get("net_expectancy_r", 0.0)
        sharpe = metrics.get("net_sharpe_ratio", 0.0)
        acc = metrics.get("accuracy", 0.0)

        if net_exp > 0 and sharpe > 0 and acc > 0.33:
            return (
                "ACCEPTED",
                True,
                None,
                [],
            )
        reasons: list[str] = []
        if net_exp <= 0:
            reasons.append(f"net_expectancy_r={net_exp} not positive")
        if sharpe <= 0:
            reasons.append(f"net_sharpe_ratio={sharpe} not positive")
        if acc <= 0.33:
            reasons.append(f"accuracy={acc} <= random (0.33)")
        return (
            "INSUFFICIENT_EVIDENCE",
            False,
            "; ".join(reasons),
            ["Improve model performance or collect more evidence"],
        )

    @staticmethod
    def _eval_model_beats_baselines(
        metrics: dict,
        baselines: dict,
    ) -> tuple[str, bool, str | None, list[str]]:
        if not baselines:
            return (
                "INSUFFICIENT_EVIDENCE",
                False,
                "No baselines available for comparison",
                ["Run BaselineLibrary.compute_baselines"],
            )

        model_exp = metrics.get("net_expectancy_r", float("-inf"))
        best_baseline_exp = max(
            (b.net_expectancy_R for b in baselines.values()),
            default=float("-inf"),
        )

        if model_exp > best_baseline_exp:
            return (
                "ACCEPTED",
                True,
                None,
                [],
            )
        return (
            "REJECTED",
            False,
            f"Model net_expectancy_r {model_exp} <= best baseline "
            f"{best_baseline_exp}",
            ["Improve model edge over baselines"],
        )

    @staticmethod
    def _eval_feature_signal(metrics: dict) -> tuple[str, bool, str | None, list[str]]:
        # Feature signal is inferred from feature importance stability
        # across folds. Metrics may include a "feature_count" or
        # "fold_feature_importance_variance" entry.
        fc = metrics.get("feature_count", 0)
        if fc < 1:
            return (
                "INSUFFICIENT_EVIDENCE",
                False,
                f"feature_count={fc} — no features to evaluate",
                ["Compute at least one feature family"],
            )
        return ("ACCEPTED", True, None, [])

    @staticmethod
    def _eval_cost_aware_filter(
        metrics: dict,
    ) -> tuple[str, bool, str | None, list[str]]:
        # Check that cost decomposition data exists
        cost_decomp = metrics.get("cost_decomposition")
        if not cost_decomp:
            return (
                "INSUFFICIENT_EVIDENCE",
                False,
                "No cost decomposition in metrics",
                ["Run cost-aware labeling pipeline"],
            )
        net_exp = metrics.get("net_expectancy_r", 0.0)
        if net_exp > 0:
            return (
                "ACCEPTED",
                True,
                None,
                [],
            )
        return (
            "REJECTED",
            False,
            f"After-cost net_expectancy_r={net_exp} is not positive",
            ["Reduce cost drag or improve gross edge"],
        )

    @staticmethod
    def _eval_training_change(
        metrics: dict,
    ) -> tuple[str, bool, str | None, list[str]]:
        # Training changes are allowed if metrics are non-degenerate
        if metrics.get("accuracy", 0) > 0 and metrics.get("n_folds", 0) > 0:
            return ("ACCEPTED", True, None, [])
        return (
            "REJECTED",
            False,
            "Training metrics are degenerate — pipeline may be broken",
            ["Verify training pipeline integrity"],
        )

    def _eval_v7_readiness(
        self,
        claim_type: ClaimType,
        passport: EvidencePassport,
    ) -> tuple[str, bool, str | None, list[str]]:
        gate_results = self._gate_mapper.map_passport_to_gates(passport)

        gate_map = {
            ClaimType.V7_RESEARCH_BACKTEST_READY: "G1",
            ClaimType.V7_COST_STRESS_READY: "G3",
            ClaimType.V7_SHADOW_READY: "G9",
            ClaimType.V7_PAPER_READY: "G9",  # paper = shadow paper gate
        }

        target_gate = gate_map.get(claim_type)
        if target_gate is None:
            return (
                "INSUFFICIENT_EVIDENCE",
                False,
                f"No gate mapped for {claim_type.value}",
                [],
            )

        gr = gate_results.get(target_gate)
        if gr is None:
            return (
                "NOT_RUN",
                False,
                f"Gate {target_gate} has not been evaluated",
                [f"Run gate {target_gate} evaluation"],
            )
        if gr.status == "PASSED":
            return ("ACCEPTED", True, None, [])
        if gr.status == "FAILED":
            return (
                "REJECTED",
                False,
                f"Gate {target_gate} failed: "
                f"{'; '.join(gr.blocking_issues)}",
                gr.missing_evidence,
            )
        return (
            "INSUFFICIENT_EVIDENCE",
            False,
            f"Gate {target_gate} status is {gr.status}",
            gr.missing_evidence,
        )


# Late import to break circular dependency
from lib.evidence_engine.evidence_passport import EvidencePassportBuilder  # noqa: E402, F811
