export const API_V3_PREFIX = '/api/v3'

export const apiRoutes = {
  symbols: () => '/api/symbols',
  health: () => `${API_V3_PREFIX}/health`,
  dashboard: () => `${API_V3_PREFIX}/dashboard`,
  calibrationStatus: () => `${API_V3_PREFIX}/calibration/status`,

  marketOverview: () => `${API_V3_PREFIX}/market/overview`,
  marketSignals: () => `${API_V3_PREFIX}/market/signals`,
  analyze: () => `${API_V3_PREFIX}/analyze`,
  klines: () => `${API_V3_PREFIX}/klines`,

  failures: () => `${API_V3_PREFIX}/failures`,
  failureSummary: () => `${API_V3_PREFIX}/failures/summary`,
  weaknessProfile: () => `${API_V3_PREFIX}/failures/weakness-profile`,
  failureAnalytics: () => `${API_V3_PREFIX}/failures/analytics`,
  failureExport: () => `${API_V3_PREFIX}/failures/export`,

  learningProfile: () => `${API_V3_PREFIX}/learning/profile`,
  learningEffectiveness: () => `${API_V3_PREFIX}/learning/effectiveness`,
  learningExport: () => `${API_V3_PREFIX}/learning/export`,

  analytics: () => `${API_V3_PREFIX}/analytics`,
  analyticsExport: () => `${API_V3_PREFIX}/analytics/export`,
  swingPatchValidation: () => `${API_V3_PREFIX}/analytics/swing-patch-validation`,
  swingPatchValidationExport: () => `${API_V3_PREFIX}/analytics/swing-patch-validation/export`,

  improvements: () => `${API_V3_PREFIX}/improvements`,
  improvementsExport: () => `${API_V3_PREFIX}/improvements/export`,

  circuitBreakerState: () => `${API_V3_PREFIX}/circuit-breaker/state`,
  circuitBreakerEvents: () => `${API_V3_PREFIX}/circuit-breaker/events`,
  circuitBreakerReset: () => `${API_V3_PREFIX}/circuit-breaker/reset`,
  circuitBreakerSettings: () => `${API_V3_PREFIX}/circuit-breaker/settings`,

  settings: () => `${API_V3_PREFIX}/settings`,
  settingsMetadata: () => `${API_V3_PREFIX}/settings/metadata`,
  alerts: () => `${API_V3_PREFIX}/alerts`,
  logs: () => `${API_V3_PREFIX}/logs`,
  traces: () => `${API_V3_PREFIX}/traces`,

  orders: () => `${API_V3_PREFIX}/orders`,
  orderClose: (orderId: string) => `${API_V3_PREFIX}/orders/${encodeURIComponent(orderId)}/close`,
  closeAllOpenOrders: () => `${API_V3_PREFIX}/orders/close-all-open`,
  portfolio: () => `${API_V3_PREFIX}/portfolio`,
  paperBalance: () => `${API_V3_PREFIX}/paper/balance`,
  paperDeposit: () => `${API_V3_PREFIX}/paper/deposit`,
  paperReset: () => `${API_V3_PREFIX}/paper/reset`,
  paperReconcile: () => `${API_V3_PREFIX}/paper/reconcile`,

  performance: () => `${API_V3_PREFIX}/performance`,
  reviewDecisionEvents: () => `${API_V3_PREFIX}/review/decision-events`,
  reviewTradeOutcomes: () => `${API_V3_PREFIX}/review/trade-outcomes`,
  reviewEngineBehavior: () => `${API_V3_PREFIX}/review/engine-behavior`,
  reviewShadowComparison: () => `${API_V3_PREFIX}/review/shadow-comparison`,
  reviewLearning: () => `${API_V3_PREFIX}/review/learning`,
  runtimeMetrics: () => `${API_V3_PREFIX}/runtime/metrics`,
  operateChampion: () => `${API_V3_PREFIX}/operate/registry/champion`,
  operateCandidates: () => `${API_V3_PREFIX}/operate/registry/candidates`,
  operateModels: () => `${API_V3_PREFIX}/operate/registry/models`,
  operatePromote: () => `${API_V3_PREFIX}/operate/registry/promote`,
  operateRollback: () => `${API_V3_PREFIX}/operate/registry/rollback`,
  operateRuntimeStatus: () => `${API_V3_PREFIX}/operate/runtime/status`,
  operateRuntimeRefreshChampion: () => `${API_V3_PREFIX}/operate/runtime/refresh-champion`,
  operateShadowEngine: () => `${API_V3_PREFIX}/operate/shadow-engine`,
  runtimeProfiles: () => `${API_V3_PREFIX}/runtime/profiles`,
  runtimeProfileSettings: (profileId: string) => `${API_V3_PREFIX}/runtime/profiles/${encodeURIComponent(profileId)}/settings`,
  runtimeProfileReadOnlyExposure: (profileId: string) => `${API_V3_PREFIX}/runtime/profiles/${encodeURIComponent(profileId)}/read-only/exposure`,
  tradeOverview: () => `${API_V3_PREFIX}/trade/overview`,
  simulationPresets: () => `${API_V3_PREFIX}/simulation-presets`,
  simulationPreset: (presetId: number) => `${API_V3_PREFIX}/simulation-presets/${presetId}`,
  simulations: () => `${API_V3_PREFIX}/simulations`,
  simulationRun: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}`,
  simulationStop: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/stop`,
  simulationForceStop: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/force-stop`,
  simulationDecisionTraces: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/decision-traces`,
  simulationDecisionTraceSummary: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/decision-trace-summary`,
  simulationDiagnostics: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/diagnostics`,
  simulationConfidenceHistogram: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/confidence-histogram`,
  simulationWhatIf: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/what-if`,
  simulationFailureAnalysis: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/failure-analysis`,
  simulationExports: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/exports`,
  simulationParityReport: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/parity-report`,
  simulationEvents: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/events`,
  simulationEventsSse: (runId: number) => `${API_V3_PREFIX}/simulations/${runId}/events-sse`,

  scans: () => `${API_V3_PREFIX}/scans`,
  scanEvents: () => `${API_V3_PREFIX}/scans/events`,
  scanEventsSse: () => `${API_V3_PREFIX}/scans/events-sse`,
  scansControl: () => `${API_V3_PREFIX}/scans/control`,
  retryJobs: () => `${API_V3_PREFIX}/jobs/retry`,
  scansPause: () => `${API_V3_PREFIX}/scans/control/pause`,
  scansResume: () => `${API_V3_PREFIX}/scans/control/resume`,
  scansStop: () => `${API_V3_PREFIX}/scans/control/stop`,
  scansStopAll: () => `${API_V3_PREFIX}/scans/control/stop-all`,
  scansForceStopAll: () => `${API_V3_PREFIX}/scans/control/force-stop-all`,
  scansTrigger: () => `${API_V3_PREFIX}/scans/control/trigger`,

  storageStatus: () => `${API_V3_PREFIX}/storage/status`,
  storageExport: () => `${API_V3_PREFIX}/storage/export`,
  storageImport: () => `${API_V3_PREFIX}/storage/import`,
  storageSeed: () => `${API_V3_PREFIX}/storage/seed`,
  storageClear: () => `${API_V3_PREFIX}/storage/clear`,
  storageClearComponents: () => `${API_V3_PREFIX}/storage/clear-components`,
  storageClearGroup: () => `${API_V3_PREFIX}/storage/clear-group`,

  signal: (signalId: string) => `${API_V3_PREFIX}/signals/${encodeURIComponent(signalId)}`,
  signalAudit: (signalId: string) => `${API_V3_PREFIX}/signals/${encodeURIComponent(signalId)}/audit`,

  selfLearningStatus: () => `${API_V3_PREFIX}/self-learning/status`,
  selfLearningProfile: () => `${API_V3_PREFIX}/self-learning/profile`,
  selfLearningMemories: () => `${API_V3_PREFIX}/self-learning/memories`,
  selfLearningReplay: (orderId: string) => `${API_V3_PREFIX}/self-learning/replays/${encodeURIComponent(orderId)}`,
  selfLearningShadow: (signalId: string) => `${API_V3_PREFIX}/self-learning/shadow/${encodeURIComponent(signalId)}`,
  selfLearningExport: () => `${API_V3_PREFIX}/self-learning/export`,

  v5Overview: () => `${API_V3_PREFIX}/v5/overview`,
  v5Models: () => `${API_V3_PREFIX}/v5/models`,
  v5Memory: () => `${API_V3_PREFIX}/v5/memory`,
  v5Comparison: () => `${API_V3_PREFIX}/v5/comparison`,
  v5Readiness: () => `${API_V3_PREFIX}/v5/readiness`,
  v5Promote: () => `${API_V3_PREFIX}/v5/promote`,
  v5Rollback: () => `${API_V3_PREFIX}/v5/rollback`,
  v5GateReport: () => `${API_V3_PREFIX}/v5/gate-report`,
  v5GateCalibration: () => `${API_V3_PREFIX}/v5/gate-calibration`,
} as const
